### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Viki101** [Pradip-p/E-Health-Care#25]

**Comment by Viki101** [comment]
not able to install

**Comment by Viki101** [comment]
I Giving to much errors

**Comment by Pradip-p** [comment]
Can you share error on email?

**Comment by Viki101** [comment]
yes i have sent you an email

**Comment by Viki101** [comment]
can't able to access admin section?

**Comment by Pradip-p** [comment]
username: admin Password: ***@***.***

**Comment by Pradip-p** [comment]
or you can add another admin using super admin section which is provided by
django default.

**Comment by Viki101** [comment]
Okay sir it is
..For That  Admin which is given on website or the Db Admin

**Comment by Viki101** [comment]
sir I'm asking about this admin which is given in site and how can we
create the admin here

**Comment by Pradip-p** [comment]
First, you need to create superuser using: python manage.py createsuperuser.
and run http:localhst:8000/admin

create a user using django default admin site and add this user to ADMIN group.

**Comment by Viki101** [comment]
Thank You Sir All Done

**Comment by Viki101** [comment]
but patient can't take any appointment

**Comment by Viki101** [comment]
from his side

**Comment by Viki101** [comment]
Bro For E healthcare project ..mass library is not getting install
it is giving me error
